name: Update feed
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
jobs:
  update:
    name: feed
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: python things
        run: |
          python -m pip install --upgrade pip
          pip install miniflux
      - name: run update
        env:
          INSTANCE: ${{ secrets.INSTANCE }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          python run.py -n 200
      - name: publish
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: reader
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
